export const routePaths = {
  homepage: '/',
  people: '/people',
  starships: '/starships',
  vehicles: '/vehicles',
  species: '/species',
  films: '/films',
  planets: '/planets',
  'people/:id': '/people/:id',
  'starships/:id': '/starships/:id',
  'vehicles/:id': '/vehicles/:id',
  'species/:id': '/species/:id',
  'films/:id': '/films/:id',
  'planets/:id': '/planets/:id',
} as const;
